export default {
    button: "none",
    accordion: "none",
    annonce: "none",
    avatar: "none",
    badge: "none",
    card: "none",
    flag: "none",
    field: "none",
    popover: "none",
    tooltip: "none",
    menu: "none",
    alert: "none",
    switch: "none",
    toast: "none",
    tabs: {
        default: "none",
        soft: "none",
        bottomIndicator: "none",
    },
};
