export { setAccordionConfig, AccordionConfig } from "./accordion";
export { setAlertConfig, AlertConfig } from "./alert";
export { setAnnonceConfig, AnnonceConfig } from "./annonce";
export { setAvatarConfig, AvatarConfig } from "./avatar";
export { setBadgeConfig, BadgeConfig } from "./badge";
export { setButtonConfig, ButtonConfig } from "./button";
export { setCardConfig, CardConfig } from "./card";
export { setMenuConfig, MenuConfig } from "./menu";
export { setFeedbackConfig, FeedbackConfig } from "./feedback";
