export default {
    button: "md",
    accordion: "md",
    annonce: "xl",
    avatar: "full",
    badge: "md",
    card: "md",
    flag: "md",
    field: "DEFAULT",
    popover: "md",
    tooltip: "md",
    menu: "md",
    alert: "md",
    switch: "md",
    toast: "md",
    tabs: {
        default: "md",
        soft: "md",
        bottomIndicator: "md",
    },
};
