import plugin from "tailwindcss/plugin";

export const visualizations = plugin(({ addBase, theme }) => {
    addBase({
        ":root": {
            "--dv-primary-50": 'theme(colors.primary.50)',
            "--dv-primary-100": 'theme(colors.primary.100)',
            "--dv-primary-200": 'theme(colors.primary.200)',
            "--dv-primary-300": 'theme(colors.primary.300)',
            "--dv-primary-400": 'theme(colors.primary.400)',
            "--dv-primary-500": 'theme(colors.primary.500)',
            "--dv-primary-600": 'theme(colors.primary.600)',
            "--dv-primary-700": 'theme(colors.primary.700)',
            "--dv-primary-800": 'theme(colors.primary.800)',
            "--dv-primary-900": 'theme(colors.primary.900)',
            "--dv-primary-950": 'theme(colors.primary.950)',

            "--dv-secondary-50": 'theme(colors.secondary.50)',
            "--dv-secondary-100": 'theme(colors.secondary.100)',
            "--dv-secondary-200": 'theme(colors.secondary.200)',
            "--dv-secondary-300": 'theme(colors.secondary.300)',
            "--dv-secondary-400": 'theme(colors.secondary.400)',
            "--dv-secondary-500": 'theme(colors.secondary.500)',
            "--dv-secondary-600": 'theme(colors.secondary.600)',
            "--dv-secondary-700": 'theme(colors.secondary.700)',
            "--dv-secondary-800": 'theme(colors.secondary.800)',
            "--dv-secondary-900": 'theme(colors.secondary.900)',
            "--dv-secondary-950": 'theme(colors.secondary.950)',

            "--dv-accent-50": 'theme(colors.accent.50)',
            "--dv-accent-100": 'theme(colors.accent.100)',
            "--dv-accent-200": 'theme(colors.accent.200)',
            "--dv-accent-300": 'theme(colors.accent.300)',
            "--dv-accent-400": 'theme(colors.accent.400)',
            "--dv-accent-500": 'theme(colors.accent.500)',
            "--dv-accent-600": 'theme(colors.accent.600)',
            "--dv-accent-700": 'theme(colors.accent.700)',
            "--dv-accent-800": 'theme(colors.accent.800)',
            "--dv-accent-900": 'theme(colors.accent.900)',
            "--dv-accent-950": 'theme(colors.accent.950)',

            "--dv-info-50": 'theme(colors.info.50)',
            "--dv-info-100": 'theme(colors.info.100)',
            "--dv-info-200": 'theme(colors.info.200)',
            "--dv-info-300": 'theme(colors.info.300)',
            "--dv-info-400": 'theme(colors.info.400)',
            "--dv-info-500": 'theme(colors.info.500)',
            "--dv-info-600": 'theme(colors.info.600)',
            "--dv-info-700": 'theme(colors.info.700)',
            "--dv-info-800": 'theme(colors.info.800)',
            "--dv-info-900": 'theme(colors.info.900)',
            "--dv-info-950": 'theme(colors.info.950)',

            "--dv-success-50": 'theme(colors.success.50)',
            "--dv-success-100": 'theme(colors.success.100)',
            "--dv-success-200": 'theme(colors.success.200)',
            "--dv-success-300": 'theme(colors.success.300)',
            "--dv-success-400": 'theme(colors.success.400)',
            "--dv-success-500": 'theme(colors.success.500)',
            "--dv-success-600": 'theme(colors.success.600)',
            "--dv-success-700": 'theme(colors.success.700)',
            "--dv-success-800": 'theme(colors.success.800)',
            "--dv-success-900": 'theme(colors.success.900)',
            "--dv-success-950": 'theme(colors.success.950)',

            "--dv-warning-50": 'theme(colors.warning.50)',
            "--dv-warning-100": 'theme(colors.warning.100)',
            "--dv-warning-200": 'theme(colors.warning.200)',
            "--dv-warning-300": 'theme(colors.warning.300)',
            "--dv-warning-400": 'theme(colors.warning.400)',
            "--dv-warning-500": 'theme(colors.warning.500)',
            "--dv-warning-600": 'theme(colors.warning.600)',
            "--dv-warning-700": 'theme(colors.warning.700)',
            "--dv-warning-800": 'theme(colors.warning.800)',
            "--dv-warning-900": 'theme(colors.warning.900)',
            "--dv-warning-950": 'theme(colors.warning.950)',

            "--dv-danger-50": 'theme(colors.danger.50)',
            "--dv-danger-100": 'theme(colors.danger.100)',
            "--dv-danger-200": 'theme(colors.danger.200)',
            "--dv-danger-300": 'theme(colors.danger.300)',
            "--dv-danger-400": 'theme(colors.danger.400)',
            "--dv-danger-500": 'theme(colors.danger.500)',
            "--dv-danger-600": 'theme(colors.danger.600)',
            "--dv-danger-700": 'theme(colors.danger.700)',
            "--dv-danger-800": 'theme(colors.danger.800)',
            "--dv-danger-900": 'theme(colors.danger.900)',
            "--dv-danger-950": 'theme(colors.danger.950)',

            "--dv-gray-50": 'theme(colors.gray.50)',
            "--dv-gray-100": 'theme(colors.gray.100)',
            "--dv-gray-200": 'theme(colors.gray.200)',
            "--dv-gray-300": 'theme(colors.gray.300)',
            "--dv-gray-400": 'theme(colors.gray.400)',
            "--dv-gray-500": 'theme(colors.gray.500)',
            "--dv-gray-600": 'theme(colors.gray.600)',
            "--dv-gray-700": 'theme(colors.gray.700)',
            "--dv-gray-800": 'theme(colors.gray.800)',
            "--dv-gray-900": 'theme(colors.gray.900)',
            "--dv-gray-925": 'theme(colors.gray.925)',
            "--dv-gray-950": 'theme(colors.gray.950)',
        },
    });
});
